default:
  pod:
    labels:
      Team: devops
      Env: prod
      Project: k8s
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Team=devops,Env=prod,Project=k8s"
  persistentVolumeClaim:
    annotations:
      ebs-tagger.kubernetes.io/ebs-additional-resource-tags: "Team=devops,Env=prod,Project=k8s"
