apiVersion: v1
kind: Service
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: kuard
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kuard
spec:
  serviceName: "kuard"
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        ports:
        - containerPort: 8080
          name: web
        volumeMounts:
        - name: tmp
          mountPath: /tmp
  volumeClaimTemplates:
  - metadata:
      name: tmp
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gp2-stateful
      resources:
        requests:
          storage: 10Gi
