apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: k8s-metadata-injector
  namespace: kube-system
  labels:
    app: k8s-metadata-injector
webhooks: []
